# Welcome to Jekyll!
#

# Site settings
title: HawkWare
description: |
  Software development for SolidWorks and SolidWorks PDM
  crafted by [Hawk Ridge Systems](http://hawkridgesys.com)
owner: Hawk Ridge Systems # or company name
owner_url: https://hawkridgesys.com
first_published: 2018 # if migrating another site, the year of your first publish
email: info@hawkwareapps.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hawkwareapps.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Hawk_Ridge_Sys
  github: https://github.com/hawkwareapps
  linkedin-square: https://www.linkedin.com/company/hawk-ridge-systems/
  facebook-official: https://www.facebook.com/hawkridgesystems/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCMdEy4D1tF8vbyc8WLhDs6g
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
